### ISSUE TITLE
Expose OpenStack tenant ID for cluster credentials

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#11]
It is currently only possible to give a tenant *name* to the Terraform provider. We should allow tenant *id* as well because this is what's included in the `OpenStack RC File v3` which you can download in the OpenStack Horizon dashboard.

https://github.com/syseleven/terraform-provider-metakube/blob/5b9d085997075189f6eec28af46c66aaf9279b2a/metakube/schema_cluster.go#L224

**Comment by stefanandres** [comment]
This is possible with >=3.0
