### ISSUE TITLE
Clarify the 'credential' parameter of metakube_cluster

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#14]
Can you please document how the `credential` parameter of `metakube_cluster` is suppose to be used? I can't remember ever stumbling about this terminology while using MetaKube.

**Comment by furkhat** [comment]
I checked and currently there is no sensible way for user to interact with it. but it is defined in the API. I think it makes sense to delete it and add again when it can be used.

**Comment by furkhat** [comment]
Deleted the field for now.
