### ISSUE TITLE
Computed attributes of node deployment

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#17]
Some attributes of `node_deployment` seem to be computed:

* spec.template.versions.*
* spec.template.labels
* spec.template.cloud.aws.tags
* spec.template.cloud.openstack.tags
* spec.template.azure.tags
* spec.template.azure.zones

I think most of them should be non computed attributes because the user is able to easiyl set them.

**Comment by baurmatt** [comment]
I think this is also the reason why you can add, but not delete labels/tags/... This should be possible IMHO

**Comment by furkhat** [comment]
You are right. Fixed in 2cb84ed5acecd151942b34e143f71fb687decc03. This will go to next release.
