### ISSUE TITLE
Should we wait until a node deployment is updated?

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#19]
On cluster/node_deployment creation, the provider waits as long as the component needs to be up and running. This is great, because as a user I'm sure that I can afterwards use the cluster.

Updating a node deployment (e.g. updating image) is a fire and forget action. The provider just returns after the API call was fired and the user can't be sure that the rollover has already happen.

Should we change this to a "waiting operation"?

**Comment by furkhat** [comment]
Yes 92e0807
