### ISSUE TITLE
Improvement: configure OIDC AuthN and AuthZ directly in cluster resource

### ISSUE THREAD

**Issue by uhinze** [syseleven/terraform-provider-metakube#22]
Would be great to avoid this manual step after setting up the cluster.

**Comment by uhinze** [comment]
Upon a closer look, the provider even encourages the use of the central admin token via the kube_config attribute. This should be discouraged from my point of view, e.g. by a warning in the docs.

**Comment by furkhat** [comment]
This is now supported with v1.2.0
