### ISSUE TITLE
Terraform provider fails while waiting for the project to be created

### ISSUE THREAD

**Issue by shahbazn** [syseleven/terraform-provider-metakube#26]
Steps to reproduce:
1) Set metakube api token env variable and source OpenStack credentials
2) Create a metakube cluster using the the following main.tf 
```
terraform {
  required_providers {
    metakube = {
      source  = "syseleven/metakube"
    }
    openstack = {
      source = "terraform-provider-openstack/openstack"
    }
  }
}

data openstack_images_image_v2 "image" {
  most_recent = true

  visibility = "public"
  properties = {
    os_distro  = "ubuntu"
    os_version = "20.04"
  }
}

provider metakube {}
resource metakube_project "project" {
  name = "terraform-project"
}

resource metakube_cluster "cluster" {
  name       = "foo"
  dc_name    = "syseleven-cbk1"
  project_id = metakube_project.project.id

  spec {
    version = "1.20.4"
    cloud {
      openstack {
      }
    }
  }
}

resource metakube_node_deployment "node_deployment" {
  name       = null // auto generate
  cluster_id = metakube_cluster.cluster.id
  spec {
    replicas = 2
    template {
      cloud {
        openstack {
          flavor          = "m1c.medium"
          image           = data.openstack_images_image_v2.image.name
        }
      }
      operating_system {
        ubuntu {
        }
      }
      versions {
        kubelet = "1.20.4"
      }
    }
  }
}
```

On the first run terraform fails with  the following error

`error while waiting for project '<project_id>' to be created: project not ready: [GET /api/v1/projects/{project_id}][403] `getProject default  &{Error:0xc00040b9b0}`

Metakube API returns 403 on get call for a project while it is being created and terraform provider should handle this error more gracefully.

**Comment by furkhat** [comment]
This is API is returning misleading responses. Introducing a hack that ensure "illusion" of flawless creation https://github.com/syseleven/terraform-provider-metakube/commit/f0b5afea22cb05aa25e367982aced4d758ed8332
