### ISSUE TITLE
Provider upgrade changes requirement of "versions" argument

### ISSUE THREAD

**Issue by justahero** [syseleven/terraform-provider-metakube#29]
After upgrading the provider to the latest release ([0.2.4](https://github.com/syseleven/terraform-provider-metakube/releases/tag/v0.2.4)) the resource `metakube_node_deployment` defines the `versions` argument inside the `spec.template` block as required, which resulted in an error when running `terraform plan`.

```
╷
│ Error: Missing required argument
│
| ...
│
│ The argument "spec.0.template.0.versions" is required, but no definition was found.
╵
```

 Previous versions declared this argument as optional, so does the [documentation](https://registry.terraform.io/providers/syseleven/metakube/latest/docs/resources/node_deployment) for this release.

This seems like a breaking change on the patch level introduced in [commit 92e08078b](https://github.com/syseleven/terraform-provider-metakube/commit/92e08078bb8f29f9f9a9090c0cffdedf64e700bc#diff-02596f998aa571b414ed1a27ab44172c16bf9c7eb01387bf1349e356321be760R147).

**Comment by furkhat** [comment]
Fixed in `v0.2.5`. Thanks for opening the issue.
