### ISSUE TITLE
Default of replica count

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#3]
The UI defaults the replica count to 3. This seems to be a valid default for a k8s cluster. I think the Terraform provider should follow this best practice.

https://github.com/syseleven/terraform-provider-metakube/blob/e50de6f8f034156337c20ebbbc3aac43b1f727eb/metakube/schema_node_deployment.go#L35

**Comment by furkhat** [comment]
thanks, changed https://github.com/syseleven/terraform-provider-metakube/commit/7c7a78c26a07defbcdefde5740856d54133e7264
