### ISSUE TITLE
Problems when updating to 0.2.7

### ISSUE THREAD

**Issue by uhinze** [syseleven/terraform-provider-metakube#32]
Hi!

I updated the plugin from 0.2.2 to 0.2.7.

When I run a `terraform plan` on my resources now, I get the following error and cannot apply any updates:
```
Error: unable to get node deployment '/<some-id>/<some-id>:metakube-dev-worker-gxnrn': &{<nil>} (*models.ErrorResponse) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface
```

When downgrading to 0.2.2, it works again. In fact, 0.2.2 -> 0.2.3 seems to be the breaking point.

Another issue came up when I tried to fix the above issue by removing the node_deployment from the state (it was empty anyway, so I just wanted to recreate it with the 0.2.7 version): the cluster remained in the state, but when running `terraform plan`, it still wanted to create a new cluster (not only a new node deployment). Is this intended?

Best
Ulrich

**Comment by furkhat** [comment]
Hello @uhinze ,

Could you please try the following:
1. `terraform init` new state with 0.2.7
2. Use `terraform import metakube_cluster....` to recover state.

You should be able to recover state and create node deployments.

In [0.2.3 release](https://github.com/syseleven/terraform-provider-metakube/releases/tag/v0.2.3) I changed how ID's of clusters and nodedeployments are stored. This was breaking change. It is expected to raise major version when bringing breaking change. But I wanted to keep `0` major version and I didn't want to release `1.0.0` before API mechanism is fixed.

**Comment by furkhat** [comment]
Should you have any trouble please reopen this issue.
