### ISSUE TITLE
Error: node deployment version cannot be greater than cluster version

### ISSUE THREAD

**Issue by etenzy** [syseleven/terraform-provider-metakube#34]
When the cluster and the Node Deployment/s are managed in the same file the following Error shows up on upgrade of the kubelet version:
```
Error: 1 error occurred:
      * node deployment version (1.20.8) cannot be greater than cluster version (1.19.12)
```

This relies on the following validation:
https://github.com/syseleven/terraform-provider-metakube/blob/781a8149a921fed32822ad04aee4f70e9e7ac5c4/metakube/resource_metakube_node_deployment_validation.go#L103-L105

I did the upgrade as follows:
```
terraform apply -target metacube_cluster.cluster
```

Is there another way than to upgrade the cluster separately?
Upgrading the Node Deployment at the same time would be a great benefit.

**Comment by furkhat** [comment]
@etenzy indeed! Sorry I missed that. Fixed with `0.3.2` release
