### ISSUE TITLE
Support flatcar inside metakube_node_deployment

### ISSUE THREAD

**Issue by worldofgeese** [syseleven/terraform-provider-metakube#35]
`metakube_node_deployment` doesn't support flatcar under `operating_system`. If `operating_system` is omitted, `terraform plan` returns:
```
│ Error: Insufficient ubuntu blocks
│ 
│   on main.tf line 63, in resource "metakube_node_deployment" "this":
│   63:       operating_system {
│ 
│ At least 1 "ubuntu" blocks are required.
╵
```

If `ubuntu` is included as such:
```
resource "metakube_node_deployment" "this" {
  cluster_id = metakube_cluster.this.id
  spec {
    min_replicas   = 2
    max_replicas   = 10
    dynamic_config = true
    template {
      cloud {
        openstack {
          flavor          = "m1c.medium"
          image           = "Flatcar Stable (2021-08-05)"
          disk_size       = 25
          use_floating_ip = true
        }
      }
      operating_system {
        ubuntu {
          dist_upgrade_on_boot = true
        }
      }
    }
  }
}
```

A user gets themselves into trouble, with the OS displayed as Ubuntu for the Flatcar Stable image:
![ubuntu-flatcar](https://user-images.githubusercontent.com/59834693/129177218-542e4296-ad84-4245-b380-4af607e65ba8.png)

I don't know what the long-term effects of this are but I'm not sure I want to find out :sweat_smile:.

Please support `flatcar` as a valid key to `operating_system` with its associated options exposed.

**Comment by furkhat** [comment]
Thanks for reporting this. I added support for Flatcar nodes and node reboot update window in `v0.4.0` version of the provider
