### ISSUE TITLE
Default of use_floating_ip

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#4]
The UI defaults to `true` for use_floating_ip. I think this is a sane default and we should adopt it in the Terraform provider.

https://github.com/syseleven/terraform-provider-metakube/blob/e50de6f8f034156337c20ebbbc3aac43b1f727eb/metakube/schema_node_deployment.go#L276

**Comment by furkhat** [comment]
I agree, thanks https://github.com/syseleven/terraform-provider-metakube/commit/f78fdf8f8060d93685f1928a6f5757234848f508
