### ISSUE TITLE
adding a node to a node deployment does a complete rolling update of all nodes

### ISSUE THREAD

**Issue by monotek** [syseleven/terraform-provider-metakube#40]
We're using the provider in version 0.5.0.

We just changed one of our node deployments from 21 to 22 nodes.

The provider added 2 new nodes, deleting an old one and proceeded to do kind of a rolling update for all other nodes too.

In the cluster we can see, that a new machineset was created:

```
k get machinesets.cluster.k8s.io -A
NAMESPACE     NAME                                AGE   DELETED   REPLICAS   AVAILABLEREPLICAS   MACHINEDEPLOYMENT        PROVIDER    OS       VERSION
kube-system   foobarcluster-builder-6d969c8ccb   34d             1          1                   foobarcluster-builder   openstack   ubuntu   1.19.12
kube-system   foobarcluster-builder-84459676df   34d             0                              foobarcluster-builder   openstack   ubuntu   1.19.12
kube-system   foobarcluster-worker-675d5dd8bc    24m             6          5                   foobarcluster-worker    openstack   ubuntu   1.19.12
kube-system   foobarcluster-worker-6bcbd54d47    34d             17         17                  foobarcluster-worker    openstack   ubuntu   1.19.12

```

This should be prevented.

**Comment by furkhat** [comment]
Hello @monotek ,
Usually when node deployment changes include updates of image or flavor fields all nodes get recreated. Simply changing replicas should not do that. Could you check if your update includes changes for fields other than "replica"?

**Comment by monotek** [comment]
This is the Terraform plan, when it happened. 
No other node deployment changes to see:

```
  # metakube_node_deployment.foobarcluster-worker will be updated in-place
  ~ resource "metakube_node_deployment" "foobarcluster-worker" {
        id                 = "foobarcluster-worker"
        name               = "foobarcluster-worker"
        # (4 unchanged attributes hidden)

      ~ spec {
          ~ replicas       = 21 -> 22
            # (3 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }
```

**Comment by furkhat** [comment]
I see. Can you provide yaml of machine sets? the ones before and after update?

**Comment by monotek** [comment]
Yes, but i would prefer to do this via helpdesk or email.

**Comment by furkhat** [comment]
Sure, helpdesk would be best.

**Comment by monotek** [comment]
Done :)

**Comment by furkhat** [comment]
This was a problem on Metakube side. We found the cause and rolled out a fix for it.

**Comment by furkhat** [comment]
@monotek could you open helpdesk ticket, I can take a look?
Also you can try seeing diff of machinesets (they're like replicasets) and see what diff caused the rollover.

**Comment by furkhat** [comment]
@monotek we found the issue. You should not experience node rollover for that particular node deployment on your next changes.
We will make sure to fix this soon so other machine deployments are not affected. Sorry you had to encounter it again.
