### ISSUE TITLE
Node pool instances should destroy one at a time on configurable timer at apply

### ISSUE THREAD

**Issue by worldofgeese** [syseleven/terraform-provider-metakube#49]
Given a destructive operation such as removing floating IPs from node pools, the provider will first:

1. Destroy as many nodes as possible down to `min_replicas`.
2. Recreate all destroyed nodes at once
3. Destroy remaining nodes one at a time as soon as new node is ready

This leads to undesirable downtimes for stateless and stateful services. Desired behavior is to maintain the existing number of replicas and to cordon, drain and destroy nodes one at a time on a configurable timer to allow for new nodes to be fully ready with services given adequate time to schedule and deploy to new nodes.

An example of desired update behavior is [here](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html).

An example of an operation to update a node pool by removing floating IPs that will immediately attempt to destroy all existing instances down to their `min_replicas`:
```
  # metakube_node_deployment.that[0] will be updated in-place
  ~ resource "metakube_node_deployment" "that" {
        id                 = "famly-metakube-prod-worker-bvd2b"
        name               = "famly-metakube-prod-worker-bvd2b"
        # (4 unchanged attributes hidden)

      ~ spec {
            # (4 unchanged attributes hidden)

          ~ template {
                # (1 unchanged attribute hidden)

              ~ cloud {

                  ~ openstack {
                      ~ image                        = "Flatcar Stable (2021-08-05)" -> "Flatcar Stable (2021-10-01)"
                      ~ instance_ready_check_timeout = "100s" -> "120s"
                        tags                         = {
                            "metakube-cluster" = "f8wkjh8f7h"
                            "system-cluster"   = "f8wkjh8f7h"
                            "system-project"   = "8b8dr7x9q8"
                        }
                      ~ use_floating_ip              = true -> false
                        # (3 unchanged attributes hidden)
                    }
                }


                # (2 unchanged blocks hidden)
            }
        }
    }
```

Relevant terraform manifest:
```
resource "metakube_node_deployment" "this" {
  count      = var.little_node_pool.count
  cluster_id = metakube_cluster.this.id
  spec {
    min_replicas   = 2
    max_replicas   = 10
    dynamic_config = true

    template {
      cloud {
        openstack {
          flavor          = var.little_node_pool.flavor
          image           = data.openstack_images_image_v2.image.name
          disk_size       = var.little_node_pool.disk_size
          use_floating_ip = var.little_node_pool.use_floating_ip
        }
      }

      operating_system {
        flatcar {
        }
      }
    }
  }
}
```

**Comment by furkhat** [comment]
Hi thanks for opening the issue and putting detailed description!
Terraform manages the state of the resource and node rollover is managed on the side of the cloud. Therefore there is nothing to do on terraform provider side.

I will discuss it with the team and we will address this on the cloud side.
