### ISSUE TITLE
Make operating_system optional

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#5]
Everything below `operating_system` is optional, hence `operating_system` should be optional as well.

https://github.com/syseleven/terraform-provider-metakube/blob/e50de6f8f034156337c20ebbbc3aac43b1f727eb/metakube/schema_node_deployment.go#L80-L107

**Comment by baurmatt** [comment]
Wait 🤔 That's not 100% correct. As there is currently only 1 OS (ubuntu) implemented, this is actually required:

```terraform
operating_system {
  ubuntu {}
}
```

Can we make `ubuntu` really optional? Currently it throws the following error without it:

```
Error: unable to create node deployment: failed to create machine deployment from template: no machine os was provided

  on main.tf line 43, in resource "metakube_node_deployment" "example_node":
  43: resource "metakube_node_deployment" "example_node" {
```

**Comment by furkhat** [comment]
Thank you I think we make ubuntu required because it won't work without it. https://github.com/syseleven/terraform-provider-metakube/commit/8d48eec6a889ad8c072c52f9c36891ea215b1d08#diff-c028c86c967f54d6e0fd5ebb9bc2f286403aa9b2993121b250a0289f583a4639R103
