### ISSUE TITLE
openstack security group is referenced by name, which might not be unique

### ISSUE THREAD

**Issue by bastibrunner** [syseleven/terraform-provider-metakube#52]
the metacube_cluster.spec.cloud.openstack.security_group reference is by name, which can have multiple hits in openstack since it might not be unique. I guess it would be better to change that to the id.

**Comment by furkhat** [comment]
Thanks for suggestion. Currently API accepts security group name and I prefer to keep terraform data model close to what API has. I will pass your suggestion to the team and if API will be changed terraform will be adjusted as well
