### ISSUE TITLE
Failed to get oidc_kube_config

### ISSUE THREAD

**Issue by hardoverflow** [syseleven/terraform-provider-metakube#53]
**Environment**:
- **Cloud provider or hardware configuration:**
```
MetaKube v2.17.3-sys11-8
OpenStack v??
```
- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):**
```
Darwin 21.2.0 x86_64
```
- **Version of terraform and used providers (`terraform version`):**
```
Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/syseleven/metakube v1.2.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.46.0
```
**Command used to invoke terraform:**
```
terraform apply -var-file=environment.tfvars
```
**Output of terraform plan:**
https://gist.github.com/hardoverflow/1652eb8c6e673824f36d12a61f70382d

**Output of terraform apply:**
https://gist.github.com/hardoverflow/8ff94495380fc8744a9f80d98ba1cb73

**Output of the warning:**
```
|
│ Warning: failed to get oidc_kube_config: OIDC settings for "ckzbw8jc2z" not found
│
│   with metakube_cluster.cluster,
│   on main.tf line 26, in resource "metakube_cluster" "cluster":
│   26: resource "metakube_cluster" "cluster" {
│
```
**Short report:**
The deployment of the cluster with terraform works how i expected. The exit code of terraform is 0. However, the warning of the metakube provider that the oidc_kube_config cannot be found is a bit annoying. Actually i don't use it.

**Comment by furkhat** [comment]
Thanks for reporting! This was fixed in v1.3.0. The warning will not appear anymore if you are not using syseleven_auth.
