### ISSUE TITLE
Improvement: Dynamic kubelet configuration

### ISSUE THREAD

**Issue by rrednoss** [syseleven/terraform-provider-metakube#55]
The web interface for creating a new machine deployment allows to override the kubelet configuration. See: https://docs.syseleven.de/metakube/de/documentation/dynamic-kubelet-config

It would be awesome if this could also be done through the Terraform provider.

**Comment by squ94wk** [comment]
This feature was deprecated in Kubernetes 1.22 and will be removed in 1.24.
Please understand that for that reason we won't add this to our TF provider.
We will however think about a suitable replacement which would also be integrated into the provider.
