### ISSUE TITLE
Document how dc_name works

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#6]
`dc_name` is probably one of the hardest parameter to understand. As a new customer I would be completely lost which value is appropriate here. We should document that it needs to be one of those:

```bash
$ curl -s -H "authorization: Bearer $METAKUBE_TOKEN" https://metakube.syseleven.de/api/v1/dc | jq -r '.[] | select(.seed!=true) | .metadata.name'
syseleven-aws-eu-central-1
syseleven-aws-eu-north-1
syseleven-aws-eu-west-1
syseleven-aws-eu-west-2
syseleven-aws-eu-west-3
syseleven-azure-centralus
syseleven-azure-eastus
syseleven-azure-northcentralus
syseleven-azure-northeurope
syseleven-azure-southcentralus
syseleven-azure-uksouth
syseleven-azure-ukwest
syseleven-azure-westcentralus
syseleven-azure-westeurope
syseleven-azure-westus
syseleven-cbk1
syseleven-dbl1
```

**Comment by furkhat** [comment]
Thank you, I added the whole command in the documentation https://github.com/syseleven/terraform-provider-metakube/commit/fcf3fdd890c691d73578c935db2bf04598f7e2f5#diff-b9df86b9f8b43f7d41ac9860d00737520cde2bfb65152476fed0c0231979977dR41
