### ISSUE TITLE
Require only project ID _or_ project name

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#67]
The provider currently requires the OpenStack project ID and name to be set. One of it should be sufficient :)
https://github.com/syseleven/terraform-provider-metakube/blob/55c0ccf0c1c1ad39ff1e4b57e217dfa007e442ce/metakube/resource_metakube_cluster_schema.go#L328-L340

**Comment by furkhat** [comment]
Hi @baurmatt , `project_name` is optional (and deprecated) in `v5.0.5`
