### ISSUE TITLE
OpenStack (and probably AWS/Azure/...) credentials get stored in the Terraform state file

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#7]
I've just realized that the Terraform state file (specifically the `metakube_cluster` resource) contains my OpenStack credentials. From a security point of view this is not good. Is it possible to keep them out of it?

**Comment by furkhat** [comment]
Actually there is a special field for that we can set to - `"Sensitive": true`, it tells terraform not to store these values in the state file
https://github.com/syseleven/terraform-provider-metakube/blob/syseleven/master/metakube/schema_cluster.go#L214
