### ISSUE TITLE
Feature Request: Create Projects with MetaKube Terraform Provider

### ISSUE THREAD

**Issue by Footur** [syseleven/terraform-provider-metakube#71]
Can you please add a new resource type to the MetaKube Terraform provider for creating projects? It would be great to have a simple way to create and manage projects with attributes like name, ID, and labels.

**Comment by furkhat** [comment]
Hello @Footur, sadly this is not possible at the moment because api token that provider uses comes from metakube API Accounts that can only be created for a project. This means project is prerequisite to API Accounts which itself is prerequisite to using the provider.
