### ISSUE TITLE
Don't require floating_ip_pool if use_floating_ip == false

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#8]
There is no need to require a floating pool name (`floating_ip_pool`) if the user disabled the use of floating ips (`use_floating_ip = false`) for worker nodes

**Comment by furkhat** [comment]
Thank you. If not specified `floating_ip_pool` is set `ext-net` so I made it optional and computed https://github.com/syseleven/terraform-provider-metakube/commit/8d48eec6a889ad8c072c52f9c36891ea215b1d08#diff-bb2cfc3cff196e1abbd3acbca173be19b37ee2d4d01ba3177f519c36b02abec9R226
