### ISSUE TITLE
Missing documentation for service_account(_token)/sshkey resource

### ISSUE THREAD

**Issue by baurmatt** [syseleven/terraform-provider-metakube#9]
There is currently no documentation available which arguments the MetaKube provider resources accept. Can you please add it? :)

**Comment by baurmatt** [comment]
I have no idea how, but it seems like I've completely missed the website/docs folder 🙈 We currently miss documentation for the following resources:

* service_account
* service_account_token
* sshkey

I think it should be also save to switch to the new documentation format -> https://www.terraform.io/docs/registry/providers/docs.html

**Comment by furkhat** [comment]
Thanks I added missing documentation and applied new documentation format https://github.com/syseleven/terraform-provider-metakube/commit/2ca0b49b9e049caecad01e4720678fb1f7a17d7c
